name = "NeuralQuantumStates"
uuid = "029a3edf-269c-4747-b97b-5d91eab07d6f"
authors = ["Alberto Mercurio"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
