name = "NeuralQuantumStates"
uuid = "029a3edf-269c-4747-b97b-5d91eab07d6f"
authors = ["Alberto Mercurio"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "<0.0.1, 1"
Pkg = "<0.0.1, 1"
SparseArrays = "<0.0.1, 1"
Test = "<0.0.1, 1"
julia = "1.7"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
